# Generated by Django 5.0 on 2023-12-22 09:57

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.datetime
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("updated_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("production_brand", models.CharField(max_length=20)),
                ("name", models.CharField()),
                ("production_country", django_countries.fields.CountryField(max_length=2)),
                ("production_year", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Showroom",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("updated_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("name", models.CharField(max_length=50)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=15)),
                ("max_car_year", models.IntegerField(null=True)),
                ("min_car_year", models.IntegerField(null=True)),
                (
                    "allowed_brands",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30), null=True, size=None
                    ),
                ),
                (
                    "allowed_countries",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django_countries.fields.CountryField(max_length=2), null=True, size=None
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("updated_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("percentage", models.DecimalField(decimal_places=1, max_digits=3)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("cars", models.ManyToManyField(to="showroom.car")),
                ("showroom", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="showroom.showroom")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CarInShowroom",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("updated_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("car", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="showroom.car")),
                ("showroom", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="showroom.showroom")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
