# Generated by Django 5.0 on 2023-12-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showroom", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="showroom",
            name="allowed_brands",
        ),
        migrations.RemoveField(
            model_name="showroom",
            name="allowed_countries",
        ),
        migrations.RemoveField(
            model_name="showroom",
            name="max_car_year",
        ),
        migrations.RemoveField(
            model_name="showroom",
            name="min_car_year",
        ),
        migrations.AddField(
            model_name="carinshowroom",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="car",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="carinshowroom",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="carinshowroom",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="discount",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="discount",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="showroom",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="showroom",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
