services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/app

    ports:
      - 8000:8000

    depends_on:
      - db

  db:

    image: postgres:15-alpine

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    ports:
      - 5432:5432

    env_file:
      - .env

  redis:
    image: redis:7.2.3

    ports:
      - 6379:6379


  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A autoRoom worker --loglevel=info
    depends_on:
      - redis
    links:
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A autoRoom beat --loglevel=info
    depends_on:
      - redis
    links:
      - redis

volumes:
  postgres_data: