# Generated by Django 5.0 on 2023-12-22 09:57

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("showroom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("updated_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=15)),
                ("email", models.EmailField(max_length=254)),
                ("username", models.CharField(max_length=30)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("updated_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("car", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="showroom.car")),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="customer.customer")),
                ("showroom", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="showroom.showroom")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseOffer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("updated_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("car", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="showroom.car")),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="customer.customer")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
