# Generated by Django 5.0 on 2023-12-22 09:58

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("showroom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("updated_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LoyaltySupplierDiscount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("updated_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("percentage", models.DecimalField(decimal_places=1, max_digits=3)),
                ("purchases_required", models.IntegerField()),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="supplier.supplier")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierCar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("updated_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("car", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="showroom.car")),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="supplier.supplier")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierSales",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("updated_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("car", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="supplier.suppliercar")),
                ("showroom", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="showroom.showroom")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SuppliersDiscount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("updated_at", models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ("percentage", models.DecimalField(decimal_places=1, max_digits=3)),
                ("car", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="showroom.car")),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="supplier.supplier")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
